### PR TITLE
Restructure to be closer to a library crate

### PR DESCRIPTION
**Pull request by Riceman2000**
I like this project and I think some people would use it as a dependency for some other Rust projects so it would be great to make it usable as a library.

Once these changes are pushed I would love to see it published to crates.io (and maybe renamed no offense lol). Windows is a mess and anything to make development better on it is awesome.

I removed some of the benchmarking but I intentionally separated out some functions so they could be benchmarked by Cargo in the future. Here are some docs on this but it is a Nightly feature right now https://doc.rust-lang.org/cargo/commands/cargo-bench.html

Things still left to do if anyone is feeling up to it:
- Add benchmarks 
- Benchmark across some different optimization settings
- Write docs for the code -> https://doc.rust-lang.org/rust-by-example/meta/doc.html
- Examples/doctests for those looking at is as a library
- Decide the easiest way to execute this code
  - Currently I left it as 
 ```
use nmuidi::prelude::*;
...
Cleaner::new("/test/path").clean()
...
```
  - It could be simpler if we change some things around but that could close the door on other functionality 🤷 

 
Reference #2 for more commentary.

Thanks!

### CODE REVIEW

**Comment by Dillonb** [comment]
Hi, thanks for the contribution! I'll look at this when I have some time and get it merged.

**Comment by Riceman2000** [comment]
Awesome, thanks! Let me know if there are any changes you'd like to see

**Comment by enqorman** [comment]
Any news?

**Comment by brasky** [comment]
Apologies for the delay! I've been looking through the changes (while learning Rust so please forgive me) and I think it looks great. 

I ran a test against the same workload in my video (my fast build cache) and it ran well. 
image


image


And you even added tests, thanks a lot!

**Pull request merged**
